name: demo_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get: ^4.6.6
  image_picker: ^1.0.7
  flutter_html: ^3.0.0-beta.2
  logger: ^2.2.0
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.0+1
  carousel_slider: ^4.2.1
  simple_barcode_scanner: ^0.1.1
  url_launcher: ^6.3.0
  flutter_paypal: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
  android_disable_fullscreen: true
  web: true
  android_width: 200
  android_height: 200
  ios_width: 200
  ios_height: 200

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/splash.png
    - assets/TexasImage.png
    - assets/card.png
